# -*- coding: utf-8 -*-
"""Exercise-6-Subjectivity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ngrktYP4jUZqk_eVCZWMu8keElxZnznU
"""

import os
API_KEY = "insert_key_here"
os.environ["WANDB_API_KEY"] = API_KEY
os.environ["WANDB_MODE"] = "disabled"

import torch
import transformers
import nltk
from nltk.corpus import wordnet,subjectivity,stopwords
from nltk.tag.perceptron import PerceptronTagger
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download("subjectivity")
nltk.download('stopwords')

def nltk_pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:
        return None

stop_words = set(stopwords.words("english"))
def tokenize_samples(samples):
    tokenized_samples = []
    for sample in samples:
        tokens = []
        # Split text into sentences
        sentences = sent_tokenize(sample)
        for sent in sentences:
            # Tokenize each sentence into words
            words = word_tokenize(sent)
            for word in words:
                # Filter out stopwords and unwanted tokens
                if '\n' in word or "\t" in word or "--" in word or "*" in word or word.lower() in stop_words:
                    continue
                if word.strip():
                    # Process the token and add to list
                    tokens.append(word.replace('"', "'").strip().lower())
        tokenized_samples.append(tokens)

    return tokenized_samples

def prepare_data_of_subj_obj():
    print(subjectivity.categories())
# print(subjectivity.sents(categories="subj"))
    subjective_sentences = subjectivity.sents(categories="subj")
    objective_sentences = subjectivity.sents(categories="obj")

    data_with_labels = []
    assert(len(subjective_sentences) == len(objective_sentences))
    for i in range(len(subjective_sentences)):
        obj_sentence = objective_sentences[i]
        subj_sentence = subjective_sentences[i]
        data_with_labels.append({"label":"obj","sentence":obj_sentence})
        data_with_labels.append({"label":"subj","sentence":subj_sentence})

    # print(upenn_tagset()) -> Μέρη του λόγου σε προτάσεις και σε τι κλήση κλπ βρίσκονται
    lemmatizer = WordNetLemmatizer()
    tagger = PerceptronTagger()
    docs = []
    labels = []
    for doc in tqdm(data_with_labels):
        sentence = " ".join(doc["sentence"])
        label = doc["label"]
        document = re.sub(r'\W', ' ', str(sentence))

        document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)

        document = re.sub(r'\s+', ' ', document, flags=re.I)

        document = document.lower()

        document = document.split()

        doc_pos = [x[1] for x in tagger.tag(document)]

        document = \
            [lemmatizer.lemmatize(token, pos=nltk_pos_tagger(pos_tag)) \
                if nltk_pos_tagger(pos_tag) != None else lemmatizer.lemmatize(token) \
            for token, pos_tag in zip(document, doc_pos)]

        document = ' '.join(document)

        docs.append(document)
        value_of_label = 0 if label == "subj" else 1
        labels.append(value_of_label)
        # labels.append(label)
    # print(docs)
    print(len(subjective_sentences),len(objective_sentences))
    return docs,labels

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from datasets import DatasetDict,load_dataset,ClassLabel
id2label = {0:"SUBJ",1:"OBJ"}
label2id = {"SUBJ":0,"OBJ":1}

MODEL = "prajjwal1/bert-small"

dataset = load_dataset("tasksource/subjectivity")
# print(dataset['train'][0])
num_classes = 2
class_label = ClassLabel(num_classes=num_classes,names=['SUBJ','OBJ'])
def convert_labels(example):
    example["labels"] = label2id[example["Label"]]
    return example
# Set aside the test split of the dataset to perform a split on it
dataset['train'] = dataset['train'].map(convert_labels)
dataset['train'] = dataset['train'].class_encode_column('labels')

test_dataset = dataset['test'].map(convert_labels)
test_dataset = test_dataset.class_encode_column('labels')

# test_dataset.cast_column("Label",class_label)
# Perform stratified split using the label
stratified_split = test_dataset.train_test_split(
    test_size=0.5,
    stratify_by_column="labels"
)

print(stratified_split['train'][0])
# Extract the new splits
validation_dataset = stratified_split['test']
test_dataset = stratified_split['train']
dataset = DatasetDict({
    'train': dataset['train'],
    'validation': validation_dataset,
    'test': test_dataset,
})

tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL, num_labels=2, id2label = id2label, label2id = label2id)

# Freeze the base model (DistilRoBERTa)
for param in model.base_model.parameters():
    param.requires_grad = False

# Count total parameters
total_params = sum(p.numel() for p in model.parameters())

# Count trainable parameters
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Total parameters: {total_params}")
print(f"Trainable parameters: {trainable_params}")

model

print(dataset)
def preprocess_function(examples):
    return tokenizer(examples["Sentence"], truncation=True)

tokenized_subj = dataset.map(preprocess_function, batched=True)

print(tokenized_subj)
print(tokenized_subj['train'][0])

import evaluate
import numpy as np

accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

import torch

def compute_metrics(p):
    predictions, labels = p

    # Ensure predictions are converted to a PyTorch tensor
    if not isinstance(predictions, torch.Tensor):
        predictions = torch.tensor(predictions)

    # Convert logits to predicted class indices
    predictions = torch.argmax(predictions, dim=1)
    # Compute metrics
    accuracy = accuracy_metric.compute(predictions=predictions.numpy(), references=labels)
    f1 = f1_metric.compute(predictions=predictions.numpy(), references=labels, average="macro")

    return {
        "accuracy": accuracy["accuracy"],
        "f1": f1["f1"]
    }

from transformers import TrainingArguments, Trainer, DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="pt") # Dynamically pads the sequences within each patch to avoid any shape misalignments

training_args = TrainingArguments(
    output_dir='./txt_cls_frozen_base/',
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
)

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_subj["train"],
    eval_dataset=tokenized_subj["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

predictions = trainer.predict(test_dataset=tokenized_subj["test"])

# Unpack the results
logits = predictions.predictions
labels = predictions.label_ids
metrics = predictions.metrics

metrics
