# -*- coding: utf-8 -*-
"""Exercise-6-POS-Tagging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSbYisqPUAW2xKFCTPLI4HmUsRE_PLPu
"""

import os
os.environ["WANDB_MODE"] = "disabled"

import torch
import transformers
import nltk
from nltk.corpus import wordnet,subjectivity,stopwords
from nltk.tag.perceptron import PerceptronTagger
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download("subjectivity")
nltk.download('stopwords')

import os
file_path_dev = "en_gum-ud-dev.conllu"
file_path_train = "en_gum-ud-train.conllu"
file_path_test = "en_gum-ud-test.conllu"
print(os.getcwd())
import pyconll
def read_conllu(path):
    data = pyconll.load_from_file(path)
    tagged_sentences=[]
    t=0
    for sentence in data:
        tagged_sentence=[]
        for token in sentence:
            if token.upos:
                t+=1
                tagged_sentence.append((token.form.lower(), token.upos))
        tagged_sentences.append(tagged_sentence)
    return tagged_sentences
data_dev = read_conllu(file_path_dev)
data_train = read_conllu(file_path_train)
data_test = read_conllu(file_path_test)

print(len(data_dev))
print(len(data_train))
print(len(data_test))
print(data_dev[0],data_train[0],data_test[0])
def load_ud_treebank_data(sentences):
    # Sample format: (word, pos_tag)

    words = []
    pos_tags = []

    for sentence in sentences:
        for word, pos in sentence:
            words.append(word)
            pos_tags.append(pos)

    return words, pos_tags
X_dev,Y_dev = load_ud_treebank_data(data_dev)
X_train,Y_train = load_ud_treebank_data(data_train)
X_test,Y_test = load_ud_treebank_data(data_test)

print(X_dev[0],Y_dev[0])
print(X_train[0],Y_train[0])
print(X_test[0],Y_test[0])

str_labels = set(Y_train + Y_dev + Y_test)

print(str_labels)

id2label = {}
label2id = {}
for l,ind in enumerate(str_labels):
    id2label[l] = ind
    label2id[ind] = l

print(id2label)
print(label2id)

from transformers import AutoTokenizer, AutoModelForTokenClassification
from datasets import DatasetDict,load_dataset,ClassLabel,Dataset
MODEL = "prajjwal1/bert-small"
DATASET = "batterydata/pos_tagging"
dataset = load_dataset("batterydata/pos_tagging")
# num_classes = len(id2label.keys())
labels = set()
for data in dataset['train']:
    new_labels = set(data["labels"])
    labels.update(new_labels)
for data in dataset['test']:
    new_labels = set(data["labels"])
    labels.update(new_labels)
num_classes = len(labels)
id2label = {}
label2id = {}
for ind,l in enumerate(labels):
    id2label[ind] = l
    label2id[l] = ind


test_dataset = dataset['test']

# Perform stratified split using the label
split_data = test_dataset.train_test_split(
    test_size=0.5,
)

# Extract the new splits
validation_dataset = split_data['test']
test_dataset = split_data['train']

dataset = DatasetDict({
    'train': dataset['train'],
    'validation': validation_dataset,
    'test': test_dataset,
})

def convert_pos_tags_to_ids(example):
    example["labels"] = [label2id[label] for label in example["labels"]]
    return example
dataset = dataset.map(convert_pos_tags_to_ids)
# dataset = dataset.cast_column("labels", ClassLabel(names=list(label2id.keys())))
# for data in dataset["train"]:
#     data["labels"] = [label2id[label] for label in data["labels"]]


# for data in dataset["test"]:
#     data["labels"] = [label2id[label] for label in data["labels"]]

# for data in dataset["validation"]:
#     data["labels"] = [label2id[label] for label in data["labels"]]


tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForTokenClassification.from_pretrained(MODEL, num_labels=num_classes, id2label = id2label, label2id = label2id)

print(dataset,len(labels),labels)
print(dataset["train"][0])

model

# Freeze the base model (DistilRoBERTa)
for param in model.base_model.parameters():
    param.requires_grad = False

# Count total parameters
total_params = sum(p.numel() for p in model.parameters())

# Count trainable parameters
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Total parameters: {total_params}")
print(f"Trainable parameters: {trainable_params}")

# def preprocess_function(examples):
#     return tokenizer(examples["words"], truncation=True,is_split_into_words=True,padding="max_length",max_length=512)
# tokenized_ud = dataset.map(preprocess_function, batched=True)

def tokenize_and_align_labels(example, max_length=128):
    # Tokenize the words (using the tokenizer)
    encoding = tokenizer(example['words'], truncation=True, padding=True,max_length=max_length, is_split_into_words=True)

    # Align the labels with tokenized words
    labels = example['labels']
    # Ensure that the length of the labels matches the tokenized length
    if len(labels) < len(encoding['input_ids']):
        # Add a placeholder label (e.g., -100) for padding tokens
        labels = labels + (['0'] * (len(encoding['input_ids']) - len(labels)))  # -100 is the ignored index for labels in Hugging Face
    else:
        # If labels exceed tokenized length, truncate the labels
        labels = labels[:len(encoding['input_ids'])]

    encoding['labels'] = labels
    return encoding

# Apply tokenization and truncation
train_data = dataset["train"].map(tokenize_and_align_labels,batched=True)
validation_data = dataset["validation"].map(tokenize_and_align_labels,batched=True)
test_data = dataset["test"].map(tokenize_and_align_labels,batched=True)

# dataset = Dataset.from_list(processed_data)
dataset_new = DatasetDict({
    "train":train_data,
    "validation":validation_data,
    "test":test_data
})

# dataset_new = dataset_new.cast_column("labels",ClassLabel(names=list(label2id.values())))
print(dataset_new)

print(dataset_new)
print(dataset_new["train"][0])

import evaluate
import numpy as np

accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

import torch

def compute_metrics(p):
    predictions, labels = p

    # Ensure predictions are converted to a PyTorch tensor
    if not isinstance(predictions, torch.Tensor):
        predictions = torch.tensor(predictions)

    # Convert logits to predicted class indices
    predictions = torch.argmax(predictions, dim=1)
    # Compute metrics
    accuracy = accuracy_metric.compute(predictions=predictions.numpy(), references=labels)
    f1 = f1_metric.compute(predictions=predictions.numpy(), references=labels, average="macro")

    return {
        "accuracy": accuracy["accuracy"],
        "f1": f1["f1"]
    }

from transformers import TrainingArguments, Trainer, DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="pt") # Dynamically pads the sequences within each patch to avoid any shape misalignments

training_args = TrainingArguments(
    output_dir='./txt_cls_frozen_base/',
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,

)

unique_val_labels = set()
for example in dataset_new["test"]:
    unique_val_labels.update(example["labels"])
print(len(unique_val_labels))

trainer = Trainer(
    model,
    training_args,
    train_dataset=dataset_new["train"],
    eval_dataset=dataset_new["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

predictions = trainer.predict(test_dataset=dataset["test"])

# Unpack the results
logits = predictions.predictions
labels = predictions.label_ids
metrics = predictions.metrics

metrics
